#!/bin/bash
set -e

echo "=== vlmocr-pipe install ==="
echo ""

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Check prerequisites
command -v node >/dev/null 2>&1 || { echo "Error: Node.js is required. Install from https://nodejs.org"; exit 1; }

# ---------------------------------------------------------------------------
# Python environment setup
#
# Preference order:
#   1. uv  — if available, creates/manages a uv-native venv at apps/worker/.venv
#            and all pip operations go through "uv pip".
#   2. venv — built-in, creates a plain virtualenv at apps/worker/.venv and
#             uses the venv's own pip.
#
# The resolved $PYTHON and $PIP are written to apps/worker/.venv/vlmocr-env.sh
# so that start.sh can source them without re-running this logic.
# ---------------------------------------------------------------------------

VENV_DIR="$SCRIPT_DIR/apps/worker/.venv"
ENV_FILE="$VENV_DIR/vlmocr-env.sh"

# Find a working system Python (used only to bootstrap the venv; never run directly)
SYS_PYTHON=""
for cand in python3 python; do
  if command -v "$cand" >/dev/null 2>&1 && "$cand" -c "import sys; assert sys.version_info >= (3,8)" >/dev/null 2>&1; then
    SYS_PYTHON="$cand"
    break
  fi
done

if command -v uv >/dev/null 2>&1; then
  # ── uv path ──────────────────────────────────────────────────────────────
  echo "[python] uv detected — using uv-managed virtualenv at apps/worker/.venv"

  # Create the venv if it doesn't exist yet (idempotent)
  if [ ! -d "$VENV_DIR" ]; then
    if [ -n "$SYS_PYTHON" ]; then
      uv venv "$VENV_DIR" --python "$SYS_PYTHON" --quiet
    else
      uv venv "$VENV_DIR" --quiet
    fi
  fi

  # Resolve the venv Python for use at runtime
  if [ -f "$VENV_DIR/bin/python" ]; then
    PYTHON="$VENV_DIR/bin/python"
  else
    PYTHON="$VENV_DIR/Scripts/python.exe"   # Windows / Git-Bash
  fi

  # Write env file consumed by start.sh
  mkdir -p "$VENV_DIR"
  cat > "$ENV_FILE" << EOF
# Auto-generated by install.sh — do not edit
VLMOCR_UV=1
VLMOCR_PYTHON="$PYTHON"
VLMOCR_VENV="$VENV_DIR"
EOF

else
  # ── venv path ─────────────────────────────────────────────────────────────
  [ -n "$SYS_PYTHON" ] || {
    echo "Error: Python 3.8+ is required. Install from https://python.org"
    exit 1
  }
  echo "[python] uv not found — using standard virtualenv at apps/worker/.venv"

  # Create the venv if it doesn't exist yet (idempotent)
  if [ ! -d "$VENV_DIR" ]; then
    "$SYS_PYTHON" -m venv "$VENV_DIR"
  fi

  # Resolve the venv Python
  if [ -f "$VENV_DIR/bin/python" ]; then
    PYTHON="$VENV_DIR/bin/python"
    PIP="$VENV_DIR/bin/pip"
  else
    PYTHON="$VENV_DIR/Scripts/python.exe"
    PIP="$VENV_DIR/Scripts/pip.exe"
  fi

  # Write env file consumed by start.sh
  mkdir -p "$VENV_DIR"
  cat > "$ENV_FILE" << EOF
# Auto-generated by install.sh — do not edit
VLMOCR_UV=0
VLMOCR_PYTHON="$PYTHON"
VLMOCR_PIP="$PIP"
VLMOCR_VENV="$VENV_DIR"
EOF
fi

# ---------------------------------------------------------------------------
# Install web dependencies
# ---------------------------------------------------------------------------
echo "[1/3] Installing web dependencies..."
cd "$SCRIPT_DIR/apps/web"
npm install --silent 2>/dev/null

# Verify better-sqlite3 native module loads against the current Node ABI.
if ! node -e "require('better-sqlite3')" >/dev/null 2>&1; then
  echo "      better-sqlite3 ABI mismatch detected — rebuilding..."
  if ! npm rebuild better-sqlite3 --build-from-source >/dev/null 2>&1 \
       || ! node -e "require('better-sqlite3')" >/dev/null 2>&1; then
    echo "      rebuild failed — wiping node_modules and reinstalling..."
    rm -rf node_modules package-lock.json
    npm install --silent 2>/dev/null
  fi
  if ! node -e "require('better-sqlite3')" >/dev/null 2>&1; then
    echo ""
    echo "Error: better-sqlite3 still won't load. You likely need build tools:"
    echo "  macOS:   xcode-select --install"
    echo "  Linux:   install build-essential and python3"
    exit 1
  fi
fi
cd "$SCRIPT_DIR"

# ---------------------------------------------------------------------------
# Install worker Python dependencies into the venv
# ---------------------------------------------------------------------------
echo "[2/3] Installing worker dependencies..."

# Re-source the env file to get $VLMOCR_UV / $VLMOCR_PYTHON etc.
# shellcheck source=/dev/null
source "$ENV_FILE"

if [ "$VLMOCR_UV" = "1" ]; then
  uv pip install -r "$SCRIPT_DIR/apps/worker/requirements.txt" \
    --python "$VLMOCR_PYTHON" --quiet 2>/dev/null
else
  "$VLMOCR_PIP" install -r "$SCRIPT_DIR/apps/worker/requirements.txt" \
    --quiet 2>/dev/null
fi

# ---------------------------------------------------------------------------
# Create data directories + initialise SQLite schema
# ---------------------------------------------------------------------------
mkdir -p "$SCRIPT_DIR/apps/web/data/storage"

echo "[3/3] Initializing database..."
cd "$SCRIPT_DIR/apps/web"
node -e "
  const Database = require('better-sqlite3');
  const fs = require('fs');
  const path = require('path');
  fs.mkdirSync(path.join('data', 'storage'), { recursive: true });
  const db = new Database(path.join('data', 'ocr.db'));
  db.exec(fs.readFileSync(path.join('src','lib','db','schema.sql'), 'utf-8'));
  const migrations = [
    \"ALTER TABLE jobs ADD COLUMN model_config TEXT NOT NULL DEFAULT '{}'\",
    'ALTER TABLE jobs ADD COLUMN failed_count INTEGER NOT NULL DEFAULT 0',
    'ALTER TABLE jobs ADD COLUMN total_input_tokens INTEGER NOT NULL DEFAULT 0',
    'ALTER TABLE jobs ADD COLUMN total_output_tokens INTEGER NOT NULL DEFAULT 0',
    'ALTER TABLE jobs ADD COLUMN total_cost REAL NOT NULL DEFAULT 0',
    'ALTER TABLE eval_models ADD COLUMN input_cost_per_1m REAL NOT NULL DEFAULT 0',
    'ALTER TABLE eval_models ADD COLUMN output_cost_per_1m REAL NOT NULL DEFAULT 0',
    'ALTER TABLE eval_models ADD COLUMN tokens_per_image INTEGER NOT NULL DEFAULT 1000',
  ];
  for (const m of migrations) { try { db.exec(m); } catch (_) { /* column exists */ } }
  db.exec(fs.readFileSync(path.join('src','lib','db','seed.sql'), 'utf-8'));
  db.close();
" || echo "      Warning: schema init failed; web app will retry on first request."
cd "$SCRIPT_DIR"

echo ""
echo "Install complete. Run ./start.sh to launch."
